// AREA 0: BOULDER GARDEN (No skills — teaches hand selection and direction)
const ROUTES_AREA_0 = [
    {
        id: 'bg1',
        name: 'Hand Choice',
        grade: 'V0',
        holdCount: 6,
        description: 'Choose your hands wisely to make it to the top',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg2',
        name: 'Shake',
        grade: 'V0',
        holdCount: 10,
        description: 'Shake out to recover some pump and make it to the top.',
        startCol: 3,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1  }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2  }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 3  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4  }, matchable: false, isRest: false, shakable: true },
            { type: 'pinch',  label: 'PINCH',  angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6  }, matchable: false, isRest: false, shakable: true },
            { type: 'sloper', label: 'SLOPER', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 7  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8  }, matchable: false, isRest: false, shakable: true },
            { type: 'crimp',  label: 'CRIMP',  angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 9  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 10 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg3',
        name: 'Chalk',
        grade: 'V0',
        holdCount: 7,
        description: 'Make good use of chalk to tackle this climb.',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 1 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false, chalkable: true },
            { type: 'jug', label: 'JUG', angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 4 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'jug', label: 'JUG', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 5, y: 6 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 7 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg4',
        name: 'Combined',
        grade: 'V1',
        holdCount: 11,
        description: 'Use all of your skills to reach the top!',
        startCol: 3,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0,   pumpRating: 2, gripDrain: 1, position: { x: 4, y: 2 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 270, pumpRating: 2, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false, shakable: true },
            { type: 'pinch',  label: 'PINCH',  angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'crimp',  label: 'CRIMP',  angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 6 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 7 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 4, y: 7 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
];
