// AREA 1: CRIMP CANYON (Teaches Cross + Reach skills unlocked at Area 0; unlocks Weight Shift at 8★)
const ROUTES_AREA_1 = [
    {
        id: 'cc1',
        name: 'Weight Shift',
        grade: 'V1',
        holdCount: 8,
        description: 'Keep your center of gravity moving to tackle this climb.',
        startCol: 3,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 90,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false, shakable: true, chalkable: true },
            { type: 'edge',   label: 'EDGE',   angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 3, y: 5 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 270, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'cc2',
        name: 'Cross',
        grade: 'V1',
        holdCount: 8,
        description: 'Bust out a good cross technique to stay on the wall.',
        startCol: 4,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 4, y: 3 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 5, y: 4 }, matchable: false, isRest: false, shakable: true, chalkable: true },
            { type: 'pocket', label: 'POCKET', angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 6 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'cc3',
        name: 'Reach',
        grade: 'V1',
        holdCount: 8,
        description: 'Long reaches lead up this rock face.',
        startCol: 2,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 1 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false, shakable: true },
            { type: 'edge',   label: 'EDGE',   angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 4, y: 3 }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false, shakable: true },
            { type: 'pocket', label: 'POCKET', angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 5 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 270, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 6 }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false, shakable: true },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 9 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'cc4',
        name: 'Combined Level 2',
        grade: 'V2',
        holdCount: 15,
        description: 'Use all the tools at your disposal to conquer this boulder.',
        startCol: 2,
        holds: [
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 1, y: 1  }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 45,  pumpRating: 1, gripDrain: 1, position: { x: 4, y: 1  }, matchable: false, isRest: false },
            { type: 'crimp',  label: 'CRIMP',  angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 0, y: 2  }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 2  }, matchable: false, isRest: false },
            { type: 'pinch',  label: 'PINCH',  angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 1, y: 3  }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 5, y: 3  }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 1, y: 4  }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 270, pumpRating: 1, gripDrain: 1, position: { x: 5, y: 4  }, matchable: false, isRest: false },
            { type: 'edge',   label: 'EDGE',   angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5  }, matchable: false, isRest: false, shakable: true, chalkable: true },
            { type: 'jug',    label: 'JUG',    angle: 315, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5  }, matchable: false, isRest: false, shakable: true, chalkable: true },
            { type: 'sloper', label: 'SLOPER', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7  }, matchable: false, isRest: false },
            { type: 'pinch',  label: 'PINCH',  angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 8  }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 3, y: 9  }, matchable: false, isRest: false },
            { type: 'jug',    label: 'JUG',    angle: 0,   pumpRating: 1, gripDrain: 1, position: { x: 4, y: 10 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
];
