// AREA 0: BOULDER GARDEN (No skill — teaches hand selection, direction)
const ROUTES_AREA_0 = [
    {
        id: 'bg1',
        name: 'Hands',
        grade: 'V0',
        holdCount: 8,
        description: 'A simple route',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 2, gripDrain: 2, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 4 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 6 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 7 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg2',
        name: 'Zig Zag',
        grade: 'V0',
        holdCount: 10,
        description: '',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 2, gripDrain: 1, position: { x: 4, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 2, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 3 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 5, y: 4 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'sloper', label: 'SLOPER', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg3',
        name: 'Little Ladder',
        grade: 'V0',
        holdCount: 10,
        description: '',
        startCol: 3,
        holds: [
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 1 }, matchable: false, isRest: false },
            { type: 'crimp', label: 'CRIMP', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 3 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 4 }, matchable: false, isRest: false, shakable: true, chalkable: true },
            { type: 'crimp', label: 'CRIMP', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 6 }, matchable: false, isRest: false },
            { type: 'pinch', label: 'PINCH', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 7 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg4',
        name: 'Snek',
        grade: 'V1',
        holdCount: 12,
        description: 'Can you climb the danger noodle?',
        startCol: 4,
        holds: [
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'crimp', label: 'CRIMP', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false, shakable: true },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 4 }, matchable: false, isRest: false, chalkable: true },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 6 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 7 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 9 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 40 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg5',
        name: 'Hands v2',
        grade: 'V0',
        holdCount: 12,
        description: 'Choose your path and make it to the top',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 3 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 3 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 4 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 5, y: 4 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 4, y: 6 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 7 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg6',
        name: 'Zig Zag v2',
        grade: 'V0',
        holdCount: 7,
        description: 'Zig or Zag, the choice is yours',
        startCol: 3,
        holds: [
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 1 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 2, gripDrain: 1, position: { x: 4, y: 2 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 2, gripDrain: 1, position: { x: 3, y: 3 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 6 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
    {
        id: 'bg7',
        name: 'Little Ladder v2',
        grade: 'V1',
        holdCount: 10,
        description: "Find the chalkable hold and don't fall!",
        startCol: 3,
        holds: [
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 1 }, matchable: false, isRest: false },
            { type: 'crimp', label: 'CRIMP', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 2 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 3 }, matchable: false, isRest: false, chalkable: true },
            { type: 'edge', label: 'EDGE', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 4 }, matchable: false, isRest: false },
            { type: 'pinch', label: 'PINCH', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 4 }, matchable: false, isRest: false },
            { type: 'pocket', label: 'POCKET', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 5 }, matchable: false, isRest: false, chalkable: true },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 1, y: 6 }, matchable: false, isRest: false },
            { type: 'sloper', label: 'SLOPER', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 6 }, matchable: false, isRest: false },
            { type: 'pinch', label: 'PINCH', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 2, y: 7 }, matchable: false, isRest: false },
            { type: 'jug', label: 'JUG', angle: 0, pumpRating: 1, gripDrain: 1, position: { x: 3, y: 8 }, matchable: false, isRest: false },
        ],
        stars: {
            completion: true,
            speed: { timeLimit: 30 },
            pumpEfficiency: { maxPump: 0 },
            gripEfficiency: true,
            flashClimb: true,
        }
    },
];
